site_name: Dynamic Positioning Platform

theme:  
  name: material
  logo: images/ship.png
  favicon: images/ship.png
  
  palette:
    primary: cyan
    accent: cyan

nav:
  - Overview: index.md
  - User guide: user_guide.md
  - Hardware: hardware.md
  - Software: software.md
  - Programs: programs.md
  - 3D Modeling: 3d_modeling.md
  - State Space: state_space.md
  - Licenses: licenses.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
